# Generated by Django 4.2.1 on 2023-09-27 15:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0002_user_role"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="role",
        ),
        migrations.AddField(
            model_name="user",
            name="investment",
            field=models.CharField(
                choices=[
                    ("crypto", "Crypto"),
                    ("agric", "Agric"),
                    ("metals", "Metals"),
                    ("stock", "Stock"),
                ],
                default="stock",
                max_length=20,
            ),
        ),
    ]
