# Generated by Django 4.2.1 on 2023-09-27 15:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0003_remove_user_role_user_investment"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="amount",
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AddField(
            model_name="user",
            name="loss",
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AddField(
            model_name="user",
            name="profit",
            field=models.FloatField(blank=True, default=100.0),
        ),
    ]
